name: Gradle CI

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Repository auschecken
      uses: actions/checkout@v3

    - name: Java 17 installieren
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: gradlew ausführbar machen
      run: chmod +x gradlew

    - name: Build und Test mit Gradle
      run: ./gradlew test
